#!/usr/bin/env python3
"""
Export duplicate questions (lower ID per group) to a text file,
then optionally delete them from the database.
"""

import os
from lecture_manager.db import get_connection
from lecture_manager.utils import print_colored, COLORS, color_text   # <-- added color_text

def get_duplicates_to_delete():
    """
    Returns a list of question dicts for rows that are duplicates (lower ID in each group).
    """
    conn = get_connection()
    cursor = conn.cursor(dictionary=True)

    # Find all duplicate groups and the max ID in each
    cursor.execute("""
        SELECT question_date, institution, level, paper, `group`, question_number, MAX(id) as keep_id
        FROM questions
        GROUP BY question_date, institution, level, paper, `group`, question_number
        HAVING COUNT(*) > 1
    """)
    groups = cursor.fetchall()

    if not groups:
        print_colored("[i] No duplicates found.", COLORS.GREEN)
        cursor.close()
        conn.close()
        return []

    # Build list of IDs to delete (all except keep_id)
    delete_ids = []
    for g in groups:
        cursor.execute("""
            SELECT id FROM questions
            WHERE question_date = %s AND institution = %s AND level = %s
              AND paper = %s AND `group` = %s AND question_number = %s
              AND id != %s
        """, (g['question_date'], g['institution'], g['level'], g['paper'], g['group'], g['question_number'], g['keep_id']))
        ids = [row['id'] for row in cursor.fetchall()]
        delete_ids.extend(ids)

    if not delete_ids:
        cursor.close()
        conn.close()
        return []

    # Fetch full rows for these IDs
    placeholders = ','.join(['%s'] * len(delete_ids))
    cursor.execute(f"""
        SELECT * FROM questions
        WHERE id IN ({placeholders})
    """, delete_ids)
    rows = cursor.fetchall()

    cursor.close()
    conn.close()
    return rows

def export_to_txt(questions, filename="duplicates_backup.txt"):
    """Export a list of question dicts to a text file in Question Bank format."""
    with open(filename, 'w', encoding='utf-8') as f:
        f.write("# Backup of duplicate questions (lower ID per group)\n")
        f.write("# Generated by backup_duplicates.py\n\n")

        for q in questions:
            # Write context fields if present
            if q.get('question_date'):
                f.write(f"Date: {q['question_date']}\n")
            if q.get('institution'):
                f.write(f"Institution: {q['institution']}\n")
            if q.get('level'):
                f.write(f"Level: {q['level']}\n")
            if q.get('paper'):
                f.write(f"Paper: {q['paper']}\n")
            if q.get('group'):
                f.write(f"Group: {q['group']}\n")
            if q.get('subject'):
                f.write(f"Subject: {q['subject']}\n")
            if q.get('marks') is not None:
                f.write(f"Marks: {q['marks']}\n")
            if q.get('chapter'):
                f.write(f"Chapter: {q['chapter']}\n")
            f.write(f"Question Number: {q['question_number']}\n")
            if q.get('nepali_transcription'):
                f.write(f"Nepali: {q['nepali_transcription']}\n")
            if q.get('english_transcription'):
                f.write(f"English: {q['english_transcription']}\n")
            if q.get('notes'):
                f.write(f"note: {q['notes']}\n")
            f.write("\n---\n")   # separator between questions

    print_colored(f"[✓] Exported {len(questions)} questions to {filename}", COLORS.GREEN)

def delete_duplicates(questions):
    """Delete the given questions from the database."""
    ids = [q['id'] for q in questions]
    if not ids:
        return
    conn = get_connection()
    cursor = conn.cursor()
    placeholders = ','.join(['%s'] * len(ids))
    cursor.execute(f"DELETE FROM questions WHERE id IN ({placeholders})", ids)
    conn.commit()
    deleted = cursor.rowcount
    cursor.close()
    conn.close()
    print_colored(f"[✓] Deleted {deleted} duplicate rows.", COLORS.GREEN)

def main():
    print_colored("[i] Looking for duplicate questions...", COLORS.BLUE)
    duplicates = get_duplicates_to_delete()

    if not duplicates:
        print_colored("[i] No duplicate questions found.", COLORS.GREEN)
        return

    print_colored(f"[i] Found {len(duplicates)} duplicate rows (lower ID per group).", COLORS.YELLOW)
    print_colored("[i] These will be exported to duplicates_backup.txt", COLORS.BLUE)

    export_to_txt(duplicates)

    print_colored("\n[i] Review the file duplicates_backup.txt", COLORS.BLUE)
    confirm = input(color_text("Delete these duplicate rows from the database? (y/n): ", COLORS.MAGENTA)).strip().lower()
    if confirm == 'y':
        delete_duplicates(duplicates)
        # Now add the unique constraint (optional)
        conn = get_connection()
        cursor = conn.cursor()
        try:
            cursor.execute("ALTER TABLE questions ADD UNIQUE INDEX unique_question (question_date, institution, level, paper, `group`, question_number)")
            conn.commit()
            print_colored("[✓] Added unique constraint successfully.", COLORS.GREEN)
        except Exception as e:
            print_colored(f"[!] Could not add unique constraint: {e}", COLORS.RED)
        finally:
            cursor.close()
            conn.close()
    else:
        print_colored("[i] No changes made. You can review the backup and delete manually later.", COLORS.YELLOW)

if __name__ == "__main__":
    main()
