# File youtube.py (unchanged)

import re
import os
import time
import yt_dlp
from .db import get_connection
from .utils import print_colored, COLORS

COOKIE_FILE = 'cookies.txt'
COOKIE_MAX_AGE = 7 * 24 * 60 * 60  # 7 days in seconds

def refresh_cookies():
    """Force‑refresh cookies from browser, update DB and cookies.txt."""
    print_colored("[i] Forcing cookie refresh...", COLORS.BLUE)
    _ensure_cookie_file(force=True)
    print_colored("[✓] Cookies refreshed successfully.", COLORS.GREEN)

def extract_video_id(url_or_id):
    if re.fullmatch(r'[0-9A-Za-z_-]{11}', url_or_id):
        return url_or_id
    patterns = [
        r'(?:v=|\/)([0-9A-Za-z_-]{11})(?:[?&]|$)',
        r'youtu\.be\/([0-9A-Za-z_-]{11})',
        r'shorts\/([0-9A-Za-z_-]{11})'
    ]
    for pattern in patterns:
        match = re.search(pattern, url_or_id)
        if match:
            return match.group(1)
    return None

def _format_cookie(cookie):
    """Format a cookie object into Netscape format line."""
    return f"{cookie.domain}\tTRUE\t{cookie.path}\t{'TRUE' if cookie.secure else 'FALSE'}\t{cookie.expires if cookie.expires else 0}\t{cookie.name}\t{cookie.value}"

def _extract_cookies_from_browser():
    """Extract cookies from browser using browser-cookie3."""
    try:
        import browser_cookie3
    except ImportError:
        print_colored("[!] browser-cookie3 not installed. Install with: pip install browser-cookie3", COLORS.YELLOW)
        return None

    browsers = [
        ('edge', browser_cookie3.edge),
        ('chrome', browser_cookie3.chrome),
        ('firefox', browser_cookie3.firefox),
        ('brave', browser_cookie3.brave),
        ('opera', browser_cookie3.opera),
    ]
    for name, get_cookies in browsers:
        try:
            print_colored(f"[i] Extracting cookies from {name}...", COLORS.BLUE)
            cookies = get_cookies(domain_name='youtube.com')
            # Filter essential cookies (optional, but keep most)
            lines = []
            for cookie in cookies:
                # Skip some cookies that might be large or unnecessary
                if cookie.name in ('__cf_bm', 'cf_clearance'):
                    continue
                lines.append(_format_cookie(cookie))
            if lines:
                cookie_data = "# Netscape HTTP Cookie File\n"
                cookie_data += "# This file was generated by browser-cookie3\n\n"
                cookie_data += "\n".join(lines)
                return cookie_data
        except Exception as e:
            print_colored(f"[!] Failed from {name}: {e}", COLORS.RED)
            continue
    return None

def _get_cookie_data_from_db():
    """Retrieve cookie data from database."""
    conn = get_connection()
    cursor = conn.cursor()
    cursor.execute("SELECT cookie_data, last_refresh FROM cookies WHERE id = 1")
    row = cursor.fetchone()
    cursor.close()
    conn.close()
    if row:
        return row[0], row[1]
    return None, None

def _update_cookie_data_in_db(cookie_data):
    """Store cookie data in database."""
    conn = get_connection()
    cursor = conn.cursor()
    # Upsert: replace if exists
    cursor.execute("REPLACE INTO cookies (id, cookie_data, last_refresh) VALUES (1, %s, NOW())", (cookie_data,))
    conn.commit()
    cursor.close()
    conn.close()

def _ensure_cookie_file(force=False):
    """
    Ensure cookies.txt exists and is fresh.
    If force=True, always re‑extract from browser and update DB.
    """
    need_refresh = force

    # Check if file exists and is fresh (if not forced)
    if not force and os.path.exists(COOKIE_FILE):
        mtime = os.path.getmtime(COOKIE_FILE)
        if time.time() - mtime > COOKIE_MAX_AGE:
            print_colored("[i] cookies.txt is older than 7 days. Refreshing...", COLORS.YELLOW)
            need_refresh = True
        else:
            return  # all good

    if not force and not os.path.exists(COOKIE_FILE):
        print_colored("[i] cookies.txt not found. Trying to create it...", COLORS.YELLOW)
        need_refresh = True

    if need_refresh:
        # Try DB first (if fresh)
        cookie_data, last_refresh = _get_cookie_data_from_db()
        if not force and cookie_data and last_refresh:
            if time.time() - last_refresh.timestamp() < COOKIE_MAX_AGE:
                print_colored("[i] Using fresh cookie data from database.", COLORS.GREEN)
                with open(COOKIE_FILE, 'w') as f:
                    f.write(cookie_data)
                return

        # Extract from browser
        print_colored("[i] Extracting cookies from browser (this may take a moment)...", COLORS.BLUE)
        cookie_data = _extract_cookies_from_browser()
        if cookie_data:
            _update_cookie_data_in_db(cookie_data)
            with open(COOKIE_FILE, 'w') as f:
                f.write(cookie_data)
            print_colored(f"[✓] cookies.txt created/refreshed.", COLORS.GREEN)
        else:
            print_colored("[!] Could not extract cookies. Falling back to browser cookies.", COLORS.YELLOW)

def fetch_youtube_title(video_id):
    """Fetch video title, managing cookies automatically."""
    _ensure_cookie_file()

    url = f"https://www.youtube.com/watch?v={video_id}"
    ydl_opts = {
        'quiet': True,
        'no_warnings': True,
        'extract_flat': True,           # fetch only metadata
        'skip_download': True,
        'ignoreerrors': True,
        'extractor_args': {
            'youtube': {
                'player_client': ['android', 'web'],  # fallback clients
                'skip': ['hls', 'dash'],
            }
        }
    }

    # Prefer cookies.txt if it exists
    if os.path.exists(COOKIE_FILE):
        ydl_opts['cookiefile'] = COOKIE_FILE
    else:
        ydl_opts['cookiesfrombrowser'] = ('edge',)

    try:
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(url, download=False)
            if info and isinstance(info, dict):
                return info.get('title')
            return None
    except Exception as e:
        print_colored(f"[!] Error fetching title for {video_id}: {e}", COLORS.RED)
        return None

def get_embed_link(video_id):
    return f"https://www.youtube.com/embed/{video_id}"
